### ISSUE TITLE
pgschemas not working with postgis backend

### ISSUE THREAD

**Issue by vikingvynotking** [lorinkoz/django-pgschemas#104]
django==3.2.11
django-pgschemas==0.8.0
PGSCHEMAS_ORIGINAL_BACKEND=django.contrib.gis.db.backends.postgis

Observed:

```
./manage.py
Traceback (most recent call last):
  File "/opt/app/./manage.py", line 21, in <module>
    main()
  File "/opt/app/./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/lib/python3.9/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/django/contrib/auth/models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/lib/python3.9/site-packages/django/db/models/options.py", line 207, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/lib/python3.9/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
  File "/usr/lib/python3.9/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "/usr/lib/python3.9/site-packages/django/db/utils.py", line 204, in create_connection
    backend = load_backend(db['ENGINE'])
  File "/usr/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.9/site-packages/django_pgschemas/postgresql_backend/base.py", line 7, in <module>
    from .introspection import DatabaseSchemaIntrospection
  File "/usr/lib/python3.9/site-packages/django_pgschemas/postgresql_backend/introspection.py", line 8, in <module>
    class DatabaseSchemaIntrospection(original_backend.DatabaseIntrospection):  # pragma: no cover
AttributeError: module 'django.contrib.gis.db.backends.postgis.base' has no attribute 'DatabaseIntrospection'
```

Expected:

manage.py commands (and django in general) function correctly.

**Comment by lorinkoz** [comment]
Thanks for the report, looking at it, incoming fix soonish.

**Comment by lorinkoz** [comment]
Fix should come as part of next release, but that one will softly deprecate Django 2. Are you on Django>=3 alread?

**Comment by vikingvynotking** [comment]
Days, months.. whatever :)

Mostly this seems to be working ok on an upgraded system. I am receiving the following error in tests, however, so I've not yet made any changes to my production deployment:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.ObjectInUse: cannot ALTER TABLE "foo_bar" because it has pending trigger events
```

Here's the migration, for completeness, which ran successfully against my dev db:

```
    operations = [
        migrations.AddField(
            model_name='bar',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='bar',
            constraint=models.UniqueConstraint(condition=models.Q(is_default=True), fields=('frob', 'is_default'), name='single_default_option'),
        ),
    ]
```
